### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#103]
C:\Users\.\Desktop\Ogar-unlimited-master\src\entity\Virus.js:164
speed = (.000005)splitMass^2 + (0.035)splitMass + 160
-----------------------^^^^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\MYNAME\Desktop\Ogar-unlimited-master\src\entity\index.js:5:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

C:\Users\MYNAME\Desktop\Ogar-unlimited-master\src>if errorlevel 1 (if not errorlevel 3 (GOTO END; ) )

C:\Users\MYNAME\Desktop\Ogar-unlimited-master\src>pause

**Comment by Lukkez** [comment]
Sorry for the --------, i can't put space instead

**Comment by Agarian** [comment]
same

**Comment by Andrews54757** [comment]
oops, il fix
