### ISSUE TITLE
wtf is this error?

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#107]
happened after an update notification:

>[Console] We have detected a update, Current version: 8.1.0 ,Available: 9.0.1
TypeError: Cannot read property 'replace' of undefined
    at Request._callback (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\O
gar-devs\Ogar-unlimited-master\srcnew'\GameServer.js:380:13)
    at Request.self.callback (C:\Users\owner\Desktop\Agar.io Stuff\Private serve
rs\Ogar-devs\Ogar-unlimited-master\srcnew'\node_modules\request\request.js:199:2
2)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\owner\Desktop\Agar.io Stuff\Private servers
\Ogar-devs\Ogar-unlimited-master\srcnew'\node_modules\request\request.js:1036:10
)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\owner\Desktop\Agar.io Stuff\Private
 servers\Ogar-devs\Ogar-unlimited-master\srcnew'\node_modules\request\request.js
:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
>

**Comment by Andrews54757** [comment]
I know, i fixed it now
