### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by DrilonA9** [AJS-development/Ogar-unlimited#1104]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

###### Error:
Hello I Wanna Say Something When I open Start.bat it say this 
```
module.js:341     throw err;     ^  Error: Cannot find module 'C:\Users\flori\Downloads\index.js'     
at Function.Module._resolveFilename (module.js:339:15)     
at Function.Module._load (module.js:290:25)     
at Function.Module.runMain (module.js:447:10)     
at startup (node.js:142:18)    
at node.js:939:3  Press any key to exit...
```
* edited my legitsoulja

**Comment by LegitSoulja** [comment]
lol, first of all you need to install ogarul correctly in its folders how it came.

**Comment by DrilonA9** [comment]
lol i dont understand you :(

**Comment by DrilonA9** [comment]
it works now but it says now

module.js:341
    throw err;
    ^

Error: Cannot find module './core/Multiverse'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\flori\Downloads\Ogar-unlimited-master\src\in
dex.js:4:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

Press any key to exit...

**Comment by LegitSoulja** [comment]
* Please download >> https://github.com/AJS-development/Ogar-unlimited/archive/master.zip
* Extract Ogar-Unlimited-master
* Install dependencies
* Done..
