### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RepahidiS** [AJS-development/Ogar-unlimited#1128]
I got this error on "removeNode" method. Someone please help me :/

`RangeError: Maximum call stack size exceeded
    at WorldModel.removeNode (C:\Users\Administrator\Desktop\Ogar\src\core\WorldModel.js:117:13)
    at GameServer.removeNode (C:\Users\Administrator\Desktop\Ogar\src\core\GameServer.js:638:16)
    at C:\Users\Administrator\Desktop\Ogar\src\gamemodes\TFFA.
js:74:16
    at C:\Users\Administrator\Desktop\Ogar\node_modules\collec
tions\generic-collection.js:49:18
    at SortedMap.<anonymous> (C:\Users\Administrator\Desktop\Ogar\node_modules\collections\generic-map.js:136:25)
    at Node.reduce (C:\Users\Administrator\Desktop\Ogar\node_m
odules\collections\sorted-set.js:590:22)
    at Node.reduce (C:\Users\Administrator\Desktop\Ogar\node_m
odules\collections\sorted-set.js:587:27)
    at Node.reduce (C:\Users\Administrator\Desktop\Ogar\node_m
odules\collections\sorted-set.js:587:27)
    at Node.reduce (C:\Users\Administrator\Desktop\Ogar\node_m
odules\collections\sorted-set.js:587:27)
    at Node.reduce (C:\Users\Administrator\Desktop\Ogar\node_m
odules\collections\sorted-set.js:593:28)`

**Comment by NatsuTheGreat** [comment]
We need more details. What needs to happen to get this problem?

**Comment by Andrews54757** [comment]
Update your server. I think it is fixed.

**Comment by Agarian** [comment]
We dont use sorted map anymore i think.
