### ISSUE TITLE
ERROR !

### ISSUE THREAD

**Issue by Cristianguzz** [AJS-development/Ogar-unlimited#1154]
/Ogar-unlimited/src/index.js:2
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by Lukkez** [comment]
Don't do npm, do **sudo nodejs index.js**, and, duplicated @Andrews54757

**Comment by Agarian** [comment]
use node v5.9.0
