### ISSUE TITLE
Tryin to run on mac?!

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1169]
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.3.6
Error: listen EACCES 0.0.0.0:88
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1214:19)
    at listen (net.js:1263:10)
    at Server.listen (net.js:1359:5)
    at StatServer.start (/Users/raphyjb/Desktop/1/src/core/StatServer.js:29:21)
    at GameServer.start (/Users/raphyjb/Desktop/1/src/core/GameServer.js:546:21)
    at ControlServer.start (/Users/raphyjb/Desktop/1/src/core/ControlServer.js:78:21)
    at Multiverse.create (/Users/raphyjb/Desktop/1/src/core/Multiverse.js:108:7)
    at Multiverse.init (/Users/raphyjb/Desktop/1/src/core/Multiverse.js:163:50)
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1

**Comment by ItzLevvie** [comment]
Use sudo to run your server if that doesn't work then change your ports.

**Comment by raphyjb** [comment]
ty how do i close the issue?

**Comment by LegitSoulja** [comment]
@raphyjb custom php links?

**Comment by firelightning13** [comment]
@raphyjb i use wampserver for local hosting or play offline

**Comment by firelightning13** [comment]
Not sure about mac though i use windows
