### ISSUE TITLE
Chatcolor.js not found

### ISSUE THREAD

**Issue by HappyZwerg** [AJS-development/Ogar-unlimited#1239]
I just updated Ogar-unlimited.

Then my server crashes with the error code:

Error: Cannot find module './commands/colorchat.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Stavros\Desktop\Desktop\Ogar-unlimited-maste
r\src\modules\CommandList.js:46:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Should i reinstall Ogar-unlimited?

**Comment by Megabyte918** [comment]
redownload the zip and extract the missing file or redo the update command
