### ISSUE TITLE
HELP Plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

### ISSUE THREAD

**Issue by HEROx29** [AJS-development/Ogar-unlimited#1244]
/root/Ogar-unlimited/src/index.js:2
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by ItzLevvie** [comment]
Use Node 5.9.0

**Comment by HEROx29** [comment]
how to install node 5.9.0

**Comment by HEROx29** [comment]
updating apt-get...
node v6.3.0 is already installed

root@agar:~/Ogar-unlimited/src# sudo node index.js.
module.js:442
    throw err;
    ^

Error: Cannot find module '/root/Ogar-unlimited/src/index.js.'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by ItzLevvie** [comment]
That's Node 6.3.0 not Node 5.9.0

**Comment by NatsuTheGreat** [comment]
You can uninstall v6.3.0 and then intstall v5.9.0
