### ISSUE TITLE
Hm wierd shit happenin with my first server..

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1264]
TypeError: Cannot read property 'length' of undefined
    at UpdateNodes.build (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\packet\UpdateNodes.js:25:85)
    at WebSocket.module.exports.start.updateMoveEngine.nodes.forEach.updateCells.getCellsInRange.cell.getNearestVirus.cell.onWVerify.client.updateClients.mainLoop.rnodes.forEach.WebSocket.sendPacket (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\core\GameServer.js:2117:22)
    at PlayerTracker.update (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\core\PlayerTracker.js:427:17)
    at null._onTimeout (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\core\GameServer.js:1600:28)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'length' of undefined
    at UpdateNodes.build (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\packet\UpdateNodes.js:25:85)
    at WebSocket.module.exports.start.updateMoveEngine.nodes.forEach.updateCells.getCellsInRange.cell.getNearestVirus.cell.onWVerify.client.updateClients.mainLoop.rnodes.forEach.WebSocket.sendPacket (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\core\GameServer.js:2117:22)
    at PlayerTracker.update (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\core\PlayerTracker.js:427:17)
    at null._onTimeout (C:\Users\Maurice\Desktop\Ogar 1\Ogar-unlimited-master\src\core\GameServer.js:1600:28)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'length' of undefined

**Comment by Megabyte918** [comment]
What version of OgarUL are you using and what did you do to produce this error

**Comment by Agarian** [comment]
if you used #1196 , don't.

**Comment by Agarian** [comment]
its not finished.

**Comment by raphyjb** [comment]
i didnt do shit and version is new one..

**Comment by raphyjb** [comment]
new thing i did was update all
so...

**Comment by raphyjb** [comment]
Server completly freeze when this happends btw!

**Comment by LegitSoulja** [comment]
Since this has been resolved I will now closed. The issue was a plugin faulty, do to a higher version of Ogarul.
