### ISSUE TITLE
Error: Cannot find module 'collections/fast-map'

### ISSUE THREAD

**Issue by Hunter2890** [AJS-development/Ogar-unlimited#1292]
module.js:341
    throw err;
    ^

Error: Cannot find module 'collections/fast-map'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Gavin\Downloads\Ogar-unlimited-master (1)\Og
ar-unlimited-master\src\core\WorldModel.js:20:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...
Ive been trying to get help with this situation for the past two weeks. As you can see I can not press any keys to install anything it will exit it so please explain to me and who ever has the same problem what to do. Thanks!

**Comment by LegitSoulja** [comment]
Open cmd, cd to your Ogar-unlimited directory, and run this command

> npm install collections

**Comment by Hunter2890** [comment]
where is cmd?

**Comment by Hunter2890** [comment]
@Agarian Now im getting 

module.js:442
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Gavin\Downloads\Ogar-unlimited-master (1)\Og
ar-unlimited-master\src\core\GameServer.js:17:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Press any key to exit...

**Comment by LegitSoulja** [comment]
npm install ws

any module that you are receiving now found do npm install whats missing. It's not that hard.

**Comment by Hunter2890** [comment]
just figured out Thanks (im kinda new to this stuff in you havent noticed)
