### ISSUE TITLE
Using the start.sh, I got this:

### ISSUE THREAD

**Issue by rydens** [AJS-development/Ogar-unlimited#1334]
Using the start.sh, I got this:
`/home/ogar/Ogar-unlimited/src/index.js:2
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
`

This is when I was trying to start it; I had already done `npm install`

**Comment by Agarian** [comment]
Must have Node version 5.9.0!
#638

**Comment by firelightning13** [comment]
Long time no seen, const Readline...

**Comment by LegitSoulja** [comment]
Readline was new in a version of node I think. I didn't exist in the old version or what you can call LTS I believe, or he's running a hella old version.
