### ISSUE TITLE
Minion error

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#143]
at GameServer.spawnPlayer (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\GameServer.js:1077:28)
    at Mode.FFA.onPlayerSpawn (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\gamemodes\FFA.js:74:20)
    at PacketHandler.setNickname (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\PacketHandler.js:115:34)
    at minionLoader.addBot (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\ai\minionLoader.js:46:21)
    at Commands.list.minion (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\modules\CommandList.js:152:32)
    at parseCommands (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\index.js:84:9)
    at C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\index.js:62:9
    at Interface._onLine (readline.js:208:5)
    at Interface._line (readline.js:549:8)
    at Interface._ttyWrite (readline.js:826:14)
TypeError: Cannot read property 'substr' of undefined
    at GameServer.spawnPlayer (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\GameServer.js:1077:28)
    at Mode.FFA.onPlayerSpawn (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\gamemodes\FFA.js:74:20)
    at PlayerTracker.minionPlayer.update (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\ai\minionPlayer.js:75:38)
    at GameServer.updateClients (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\GameServer.js:1046:39)
    at GameServer.mainLoop (C:\Users\Lucas\Desktop\Agar.io\Ogar-unlimited-master\src\GameServer.js:931:14)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Andrews54757** [comment]
I fixed it

**Comment by Andrews54757** [comment]
Also, if the error persists, do the update command

**Comment by Lukkez** [comment]
Thx, not more happening
