### ISSUE TITLE
Cant play Ogar at all.

### ISSUE THREAD

**Issue by Dreanor302** [AJS-development/Ogar-unlimited#1432]
So I had an Ogar server, which was running smooth and was completely updated, but I decided to mess around with the config settings which made my play blob really unplayable, I then had to delete my Ogar file and download it again but after downloading and doing everything I usually did to start up I got this error message. ( I have Windows 10. )
module.js:341
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Jordan\Desktop\Ogar-unlimited-Original\src\modules\CommandList.js:8:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

**Comment by ItzLevvie** [comment]
Do ```npm install request```

**Comment by UltraSirius** [comment]
Ogar Unlimited Is Made from Node.js And/Maybe Language C++ You Must Install Node.js, if u have node.js go at your ogar folder and src and you will see Install Dependies ( Excuse For my english I am A Filipino) And There You Go.
