### ISSUE TITLE
error when removing minions

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#151]
TypeError: Cannot read property 'mass' of null
   at PlayerTracker.minionPlayer.update (C:\Users\owner\Downloads\ogar binary\l
gs\ai\minionPlayer.js.jx:106:26)
   at GameServer.updateClients (C:\Users\owner\Downloads\ogar binary\logs\GameS
rver.js.jx:1047:39)
   at GameServer.mainLoop (C:\Users\owner\Downloads\ogar binary\logs\GameServer
js.jx:932:14)
   at wrapper [as _onTimeout] (timers.js:277:14)
   at Timer.listOnTimeout [as ontimeout] (timers.js:120:15)

**Comment by Andrews54757** [comment]
Fixed
