### ISSUE TITLE
BotPlayer.js error

### ISSUE THREAD

**Issue by firelightning13** [AJS-development/Ogar-unlimited#180]
```
TypeError: Cannot read property '0' of undefined
    at PlayerTracker.BotPlayer.getBiggest (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\ai\BotPlayer.js:494:21)
    at GameServer.ejectMass (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\GameServer.js:1475:23)
    at PlayerTracker.BotPlayer.decide (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\ai\BotPlayer.js:373:29)
    at PlayerTracker.BotPlayer.update (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\ai\BotPlayer.js:171:8)
    at GameServer.updateClients (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\GameServer.js:1133:35)
    at GameServer.mainLoop (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\GameServer.js:1018:10)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by Andrews54757** [comment]
fixed
