### ISSUE TITLE
Wtf is this error?

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#200]
TypeError: Cannot read property 'toString' of undefined
    at fillChar (C:\Users\Lucas\Desktop\Filmes\Ogar-unlimited-master\src\modules\CommandList.js:19:20)
    at Commands.list.playerlist (C:\Users\Lucas\Desktop\Filmes\Ogar-unlimited-master\src\modules\CommandList.js:2445:17)
    at parseCommands (C:\Users\Lucas\Desktop\Filmes\Ogar-unlimited-master\src\index.js:77:5)
    at C:\Users\Lucas\Desktop\Filmes\Ogar-unlimited-master\src\index.js:55:5
    at Interface._onLine (readline.js:208:5)
    at Interface._line (readline.js:549:8)
    at Interface._ttyWrite (readline.js:826:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)

All my friends have this error, LOL

**Comment by StormGS5** [comment]
so do i

**Comment by MichaelLeeHobbs** [comment]
There is a bug on line src\modules\CommandList.js:2445:17 I will push a pull request in a few minutes.

**Comment by MichaelLeeHobbs** [comment]
I'm not seeing this error. I wonder if this might be related to the two bugs I found earlier and did a pull request for.
