### ISSUE TITLE
How to use ogar-unlimited heroku?

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#202]
I can't control the server, how to control?

**Comment by mogokcp** [comment]
Heroku does not have ssh. And it sucks, really.

**Comment by Lukkez** [comment]
OpenShift work?

**Comment by ItzLevvie** [comment]
Use c9.io or koding.com

**Comment by Lukkez** [comment]
I will use c9.io, not is good for me

**Comment by Lukkez** [comment]
Sorry, the server open but i can't connect, i get ip by ifconfig, i need something more?

**Comment by ItzLevvie** [comment]
You'll need to change 443 to something like 8080.

**Comment by Lukkez** [comment]
Oh nvm, i solved, the ip is private and to connect i use http://agar.io/?ip=snakeagario-lukkez.c9users.io you can test too

**Comment by problemsofworld** [comment]
lukkez help I wanna make sever like u plz help me I don't know how

**Comment by Andrews54757** [comment]
1. make a account at c9.io
2. put this repos url in the git box
3. fill in other boxes (like name)
3. press create
4. then in config in ogar unlimited, turn vps to 1
5. run the server using sudo node src/index.js

**Comment by problemsofworld** [comment]
7. didn't got it plz explain more :(

**Comment by problemsofworld** [comment]
where's config and vps

**Comment by problemsofworld** [comment]
number 8 u mean run it on my pc ?

**Comment by problemsofworld** [comment]
tried to run with out vps that's what it give me module.js:338                                                                                                                                                                                                                                                                                 
    throw err;                                                                                                                                                                                                                                                                                
    ^                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                              
Error: Cannot find module 'request'                                                                                                                                                                                                                                                           
    at Function.Module._resolveFilename (module.js:336:15)                                                                                                                                                                                                                                    
    at Function.Module._load (module.js:286:25)                                                                                                                                                                                                                                               
    at Module.require (module.js:365:17)                                                                                                                                                                                                                                                      
    at require (module.js:384:17)                                                                                                                                                                                                                                                             
    at Object.<anonymous> (/home/ubuntu/workspace/src/modules/CommandList.js:8:15)                                                                                                                                                                                                            
    at Module._compile (module.js:434:26)                                                                                                                                                                                                                                                     
    at Object.Module._extensions..js (module.js:452:10)                                                                                                                                                                                                                                       
    at Module.load (module.js:355:32)                                                                                                                                                                                                                                                         
    at Function.Module._load (module.js:310:12)                                                                                                                                                                                                                                               
    at Module.require (module.js:365:17)

**Comment by problemsofworld** [comment]
turned on my vps and it give Your code is running at https://agario12-problemsofworld.c9users.io.                                                                                                                                                                                                                          
Important: use process.env.PORT as the port and process.env.IP as the host in your scripts!                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                              
Debugger listening on port 15454                                                                                                                                                                                                                                                              
module.js:338                                                                                                                                                                                                                                                                                 
    throw err;                                                                                                                                                                                                                                                                                
    ^                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                              
Error: Cannot find module 'request'                                                                                                                                                                                                                                                           
    at Function.Module._resolveFilename (module.js:336:15)                                                                                                                                                                                                                                    
    at Function.Module._load (module.js:286:25)                                                                                                                                                                                                                                               
    at Module.require (module.js:365:17)                                                                                                                                                                                                                                                      
    at require (module.js:384:17)                                                                                                                                                                                                                                                             
    at Object.<anonymous> (/home/ubuntu/workspace/src/modules/CommandList.js:8:15)                                                                                                                                                                                                            
    at Module._compile (module.js:434:26)                                                                                                                                                                                                                                                     
    at Object.Module._extensions..js (module.js:452:10)                                                                                                                                                                                                                                       
    at Module.load (module.js:355:32)                                                                                                                                                                                                                                                         
    at Function.Module._load (module.js:310:12)                                                                                                                                                                                                                                               
    at Module.require (module.js:365:17)                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              
Process exited with code: 1

**Comment by Andrews54757** [comment]
you need to do npm install before hand

**Comment by Andrews54757** [comment]
or do npm install request

**Comment by Andrews54757** [comment]
and do npm install ws

**Comment by Andrews54757** [comment]
and i mean run it on c9

**Comment by problemsofworld** [comment]
wait how to do npm install in c9.io :/

**Comment by problemsofworld** [comment]
thxs now it works :) :+1:
