### ISSUE TITLE
Crontab linux command ubuntu Help!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#204]
Hello,
I got so tried to find solution that why I ask here,I can't use crontab with Ogar-unlimited,because I need to open server from cd [directorypath] in commandprompt/terminal,I can screen it to prevent terminal from close after I close it,but the main problem that crontab can't reopen server if it is crash,so any idea or help please?.also crontab work normaly with me for others ogar.
Thank you.

**Comment by Andrews54757** [comment]
yes, for the command, do `sudo node (yourpathtoindex.js)` also, other ogars are also the same,

**Comment by eevaqueen** [comment]
Thank you,but it didn't work because others ogar not need cd it to Ogar-unlimited/src,when i do what you said it say error,I used this one but it didn't work "/cd/Ogar-unlimited/src/ node index.js" can you help me plz?.

**Comment by Andrews54757** [comment]
no take out the cd and do `node Ogar-unlimited/src/index.js`

**Comment by eevaqueen** [comment]
Thank you it work,but it open the "gameserver.ini" in dir file not "Ogar-unlimited/src/gameserver.ini", because i have 2 gameserver.ini,so when gameserver.ini dir file open, the customskins.txt not work and it is enable with skins in the gameserver.ini the only skin working is <spy>,but when i open "Ogar-unlimited/src/gameserver.ini" and start game with command "cd Ogar-unlimited/src sudo node index.js" all skins work prefect!,so do you know the reason? sorry for ask alot but really i can't found my question.
Thank you.

**Comment by Andrews54757** [comment]
I know, so from now on, put config in the one in directiry file, not in original

**Comment by eevaqueen** [comment]
I do what you said and nothing happen,skins only work with "cd Ogar-unlimited/src sudo node index.js",I need to move or change anything to make it work ? in directory file?
thanks.

**Comment by Andrews54757** [comment]
So, where is the gameserver.ini file duplicated

**Comment by eevaqueen** [comment]
in directory file and /Ogar-unlimited/src/gameserver.ini

**Comment by Andrews54757** [comment]
delete the config files in the directory file and move the config files from src into the directory file and your done!

**Comment by eevaqueen** [comment]
nothing happen,only spy skin showing,i hope you don't get mad from me.

**Comment by Andrews54757** [comment]
Did you move the customskins.txt file too?

**Comment by eevaqueen** [comment]
no i didnt i only moved gameserver.ini without duplicates.

**Comment by Andrews54757** [comment]
Your supposed to move all configure files, tat includes bot names, custom skins, and other txt files and other ini files.

**Comment by eevaqueen** [comment]
Thank you so much,it work now!!! WOW :+1:

**Comment by ZuckerGames** [comment]
help me
Error: listen EACCES 0.0.0.0:88                                                                                                                       
    at Object.exports._errnoException (util.js:870:11)                                                                                                
    at exports._exceptionWithHostPort (util.js:893:20)                                                                                                
    at Server._listen2 (net.js:1221:19)                                                                                                               
    at listen (net.js:1270:10)                                                                                                                        
    at Server.listen (net.js:1366:5)                                                                                                                  
    at StatServer.start (/home/ubuntu/workspace/Ogar-unlimited-master/src/core/StatServer.js:29:21)                                                   
    at GameServer.start (/home/ubuntu/workspace/Ogar-unlimited-master/src/core/GameServer.js:478:21)                                                  
    at ControlServer.start (/home/ubuntu/workspace/Ogar-unlimited-master/src/core/ControlServer.js:57:21)                                             
    at null._onTimeout (/home/ubuntu/workspace/Ogar-unlimited-master/src/index.js:39:38)                                                              
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by LegitSoulja** [comment]
@ZuckerGames Obviously, You already have port 88 in use.. Change the port in ./settings/advConfig.ini

**Comment by Agarian** [comment]
no, EACCES is a permissions issue. EADDERNUISE is when a status port is in use.

**Comment by LegitSoulja** [comment]
@Agarian yea, mybad :/

**Comment by ZuckerGames** [comment]
now will not let me enter the server
picture: http://i.imgur.com/5AJEc2F.png

**Comment by LegitSoulja** [comment]
@ZuckerGames Are you using agar.io client?

**Comment by ZuckerGames** [comment]
Which one?

**Comment by Agarian** [comment]
or use http://play.ogarul.tk

**Comment by ZuckerGames** [comment]
[Console] We have detected a update, Current version: 16.6.8 ,Available: 16.7.5
[Console] Update Details: Multiverse update. You can now have as many servers you want in one server! (and control them) (P.S. Sorry for the many updates, Development is on steroids)
[Console] To update quickly, use the update command!

**Comment by ZuckerGames** [comment]
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (/home/nitrous/Ogar-unlimited/src/core/GameServer.js:1545:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by LegitSoulja** [comment]
@ZuckerGames Did you recently update node again? Don't use any node's version higher than 5.9.0 for right now..

**Comment by ZuckerGames** [comment]
as I know my ip from a ubuntu?

**Comment by LegitSoulja** [comment]
@ZuckerGames this has nothing to do with your ip.

**Comment by ZuckerGames** [comment]
is that I supported an ip and not let me enter example zuckergames-9253.nitrouspro. com:3031

**Comment by LegitSoulja** [comment]
@ZuckerGames If you are local hosting, and have your ports port forwarded, then yes if you set up a domain correctly to your local ip address via a cname, or a record you could redirect that domain to your ip address.

**Comment by ZuckerGames** [comment]
sorry is that I literally speak Spanish

**Comment by ZuckerGames** [comment]
zuckergames: ~/Ogar-unlimited/src $ node index
 
/home/zuckergames/Ogar-unlimited/src/index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by Agarian** [comment]
You MUST have node v5.9.0

**Comment by Megabyte918** [comment]
does anyone even look at the troubleshooting guide...

**Comment by ZuckerGames** [comment]
a vpn free

**Comment by Agarian** [comment]
@Megabyte918 prob not...
