### ISSUE TITLE
EACCES Error

### ISSUE THREAD

**Issue by firelightning13** [AJS-development/Ogar-unlimited#211]
```
Error: listen EACCES 0.0.0.0:376
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at GameServer.startStatsServer (/home/ubuntu/workspace/src/GameServer.js:2195:19)
    at GameServer.start (/home/ubuntu/workspace/src/GameServer.js:585:8)
    at Object.<anonymous> (/home/ubuntu/workspace/src/index.js:38:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```
I tried with c9, this whats happened, and i cant join the server :/
I think i did something wrong

**Comment by ItzLevvie** [comment]
Change ```serverPort = 443`` to 8080 and ```serverStatsPort = 88``` to 8081.

**Comment by ItzLevvie** [comment]
Change ```serverPort = 443``` to 8080 and ```serverStatsPort = 88``` to 8082.

**Comment by firelightning13** [comment]
Ok it works thanks @ItzLevvie

**Comment by Andrews54757** [comment]
The best way is to change VPS to 1 in config

**Comment by firelightning13** [comment]
@Andrews54757 I did. I just need to change port thats all
