### ISSUE TITLE
I got this on a fresh updated version of Ogar Unlimited

### ISSUE THREAD

**Issue by NatsuTheGreat** [AJS-development/Ogar-unlimited#238]
````
Error: Uncaught, unspecified "error" event. (reserved fields must be empty)
    at WebSocket.emit (events.js:144:17)
    at Receiver.onerror (C:\Users\Downloads\Ogar-master2\Ogar-master2\node_modules\ws\lib\WebSocket.js:832:10)
    at Receiver.error (C:\Users\Downloads\Ogar-master2\Ogar-master2\node_modules\ws\lib\Receiver.js:317:8)
    at Receiver.processPacket (C:\Users\Downloads\Ogar-master2\Ogar-master2\node_modules\ws\lib\Receiver.js:191:12)
    at Receiver.add (C:\Users\Downloads\Ogar-master2\Ogar-master2\node_modules\ws\lib\Receiver.js:91:24)
    at Socket.firstHandler (C:\Users\Downloads\Ogar-master2\Ogar-master2\node_modules\ws\lib\WebSocket.js:774:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
````

**Comment by NovaHowl** [comment]
Hmm, so this was a completely fresh version? I honestly don't know how this worked for me but I had a similar error after installing dependencies and trying to run it, just extract it again and click the 'Install Dependencies For Windows' batch file. If that doesn't work try re-installing node.

**Comment by firelightning13** [comment]
Try to do "npm install" again?

**Comment by NatsuTheGreat** [comment]
This happened when I used my bots on the server. I don't think this is really anything about the Dependencies.

**Comment by Lukkez** [comment]
Hmm, this look the web socket have a problem

**Comment by Andrews54757** [comment]
it is a module thing. I updated the pakage.json now so it now uses the last working version of ws
