### ISSUE TITLE
Cannot read property 'config' of undefined - New Update Error

### ISSUE THREAD

**Issue by hartsindale** [AJS-development/Ogar-unlimited#249]
After updating to the new server version, I get that error.

(yes, I instantly updated)

TypeError: Cannot read property 'config' of undefined
    at Cell.collisionCheck2 (/root/Ogar-unlimited/src/entity/Cell.js:163:20)
    at GameServer.getCellsInRange (/root/Ogar-unlimited/src/GameServer.js:1977:16)
    at GameServer.updateMoveEngine (/root/Ogar-unlimited/src/GameServer.js:1498:21)
    at GameServer.cellTick (/root/Ogar-unlimited/src/GameServer.js:1045:8)
    at GameServer.mainLoop (/root/Ogar-unlimited/src/GameServer.js:1085:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

**Comment by Andrews54757** [comment]
fixed
