### ISSUE TITLE
Cannot Read Property 'gameServer'

### ISSUE THREAD

**Issue by CheikoAsami** [AJS-development/Ogar-unlimited#251]
When it says the game was resumed this error appears: TypeError: Cannot read property 'gameServer' of null
    at Cell.collisionCheck2 (C:\Users\name\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\entity\Cell.js:163:15)
    at GameServer.getCellsInRange (C:\Users\name\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\GameServer.js:1977:16)
    at GameServer.updateMoveEngine (C:\Users\name\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\GameServer.js:1498:21)
    at GameServer.cellTick (C:\Users\name\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\GameServer.js:1045:8)
    at GameServer.mainLoop (C:\Users\name\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\GameServer.js:1085:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by Andrews54757** [comment]
fixed
