### ISSUE TITLE
This bug.

### ISSUE THREAD

**Issue by fodse** [AJS-development/Ogar-unlimited#303]
Happened on a fresh version.

[Game] Loaded stats server on port 88
[Game] Listening on port 4545
[Game] Current game mode is Free For All
[Autopause] The Game Was Paused to save memory. Join the game to resume!
TypeError: this.clients[i].playerTracker.antiTeamTick is not a function
    at GameServer.updateClients (C:\Users\blabla\Desktop\Ogar-unlimited-master\src\GameServer.js:1272:39)
    at GameServer.mainLoop (C:\Users\blabla\Desktop\Ogar-unlimited-master\src\GameServer.js:1107:14)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: Cannot set property 'x' of undefined
    at PacketHandler.handleMessage (C:\Users\blabla\Desktop\Ogar-unlimited-master\src\PacketHandler.js:81:32)
    at emitTwo (events.js:100 :13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onbinary (C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:537:18
    at Receiver.applyExtensions (C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:531:14
    at Receiver.flush (C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:340:3)
    at Receiver.opcodes.2.finish (C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:542:12)
    at Receiver.expectHandler (C:\Users\blabla\Desktop\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:516:33)

**Comment by firelightning13** [comment]
That's weird, its fine for me (the fresh version)

**Comment by PrinceDark9243** [comment]
Me too i am getting this error @Andrews54757 ?

**Comment by ItzLevvie** [comment]
I think @Andrews54757 merged Cell.js into PlayerTracker js

**Comment by Andrews54757** [comment]
no that was a mistake

**Comment by Andrews54757** [comment]
fixed, it was my stupid clipboard not working
