### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#305]
when changing gamemodes in console

TypeError: Cannot read property 'x' of undefined
    at PlayerTracker.getSpectateNodes (/home/ubuntu/workspace/src/PlayerTracker.js:546:52)
    at PlayerTracker.calcViewBox (/home/ubuntu/workspace/src/PlayerTracker.js:490:21)
    at PlayerTracker.update (/home/ubuntu/workspace/src/PlayerTracker.js:310:31)
    at GameServer.updateClients (/home/ubuntu/workspace/src/GameServer.js:1273:39)
    at GameServer.mainLoop (/home/ubuntu/workspace/src/GameServer.js:1107:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by XtremePlayzCODE** [comment]
Make sure to do gamemode <gamemode number value> instead of change blah blah blah

**Comment by Agarian** [comment]
yah i did

**Comment by Andrews54757** [comment]
the gamemode command is not fully functional as regular ogar says
