### ISSUE TITLE
Error: Cannot find module 'request' (module.js:338)

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#307]
I get this message everytime I load up the master branch of OgarUnlimited:

module.js:338
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\CMorgan513.Nicole-HP\Desktop\Ogar-unlimited-
master\Ogar-unlimited-master\src\modules\CommandList.js:8:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Press any key to exit...

WTF?

**Comment by firelightning13** [comment]
Do install dependencies, or just do npm install request
