### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#325]
>ReferenceError: gameServer is not defined
    at GameServer.connectionEstablished (/home/ubuntu/workspace/src/GameServer.js:471:35)
    at emitOne (events.js:77:13)
    at WebSocketServer.emit (events.js:169:7)
    at /home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:88:14
    at completeHybiUpgrade2 (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:274:5)
    at completeHybiUpgrade1 (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:299:13)
    at WebSocketServer.handleHybiUpgrade (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:327:3)
    at WebSocketServer.handleUpgrade (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:164:26)
    at Server.<anonymous> (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:86:12)
    at emitThree (events.js:97:13)
>change playerMaxMass 150000
[Console] Set playerMaxMass to 150000
>ReferenceError: gameServer is not defined
    at GameServer.connectionEstablished (/home/ubuntu/workspace/src/GameServer.js:471:35)
    at emitOne (events.js:77:13)
    at WebSocketServer.emit (events.js:169:7)
    at /home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:88:14
    at completeHybiUpgrade2 (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:274:5)
    at completeHybiUpgrade1 (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:299:13)
    at WebSocketServer.handleHybiUpgrade (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:327:3)
    at WebSocketServer.handleUpgrade (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:164:26)
    at Server.<anonymous> (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:86:12)
    at emitThree (events.js:97:13)

**Comment by Andrews54757** [comment]
fixed
