### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by ortex112** [AJS-development/Ogar-unlimited#370]
when i make install Dependencies it installs all then when i click Start.bat it makes that error.
module.js:341
    throw err;
    ^

Error: Cannot find module 'vuvuzela'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\ortex\Desktop\Ogar-unlimited-master\node_modules\pouchdb\lib\index.js:20:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...
 Please Help me.
Thanks.

**Comment by Lukkez** [comment]
``npm install vuvuzela`` install this

**Comment by ortex112** [comment]
i made that and it wrote to me that
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

Press any key to exit...

**Comment by Andrews54757** [comment]
you cannot use the update command
