### ISSUE TITLE
error @ dev

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#373]
**this:**

/home/ubuntu/workspace/src/core/GameServer.js:1131
          continue;
          ^^^^^^^^

SyntaxError: Illegal continue statement
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/src/core/ControlServer.js:6:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

happens on lines 1131, 1135, and 1139 in gameserver.js
(changed it back to return; on my c9)

**Comment by Agarian** [comment]
and

ReferenceError: Entity is not defined
    at GameServer.spawnPlayer (/home/ubuntu/workspace/src/core/GameServer.js:872:24)
    at Mode.FFA.onPlayerSpawn (/home/ubuntu/workspace/src/gamemodes/FFA.js:77:16)
    at PacketHandler.setNickname (/home/ubuntu/workspace/src/core/PacketHandler.js:127:30)
    at PacketHandler.handleMessage (/home/ubuntu/workspace/src/core/PacketHandler.js:56:12)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (/home/ubuntu/workspace/node_modules/ws/lib/WebSocket.js:823:10)
    at /home/ubuntu/workspace/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/home/ubuntu/workspace/node_modules/ws/lib/Receiver.js:364:5)
    at /home/ubuntu/workspace/node_modules/ws/lib/Receiver.js:531:14

happens when u try to join, this major update DEFINITELY needs to be delayed.

**Comment by Andrews54757** [comment]
no, your issue is not actually an issue, be sure to use the master branch and dont use the update command even if you use the new one

**Comment by Megabyte918** [comment]
@Agarian @firelightning13 fixed the first one
