### ISSUE TITLE
Bug//Error ?!

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#374]
iam having this error when trying to open the server 
C:\Users\Anony\Desktop\Ogar-unlimited-master\src\index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Press any key to exit...
Help me plz

**Comment by Agarian** [comment]
the major update needs to be delayed for a while.

**Comment by NoorAgario** [comment]
:(

**Comment by Andrews54757** [comment]
no, there is an error because you need to update your nodejs. the old one doesnt support const
