### ISSUE TITLE
Experimental mode not working

### ISSUE THREAD

**Issue by jrgryph** [AJS-development/Ogar-unlimited#391]
TypeError: Cannot read property 'getSize' of undefined
    at Mode.Experimental.spawnMotherCell (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\gamemodes\Experimental.js:56:20)
    at Mode.Experimental.onTick (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\gamemodes\Experimental.js:126:10)
    at GameServer.gameModeTick (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\core\GameServer.js:1473:21)
    at GameServer.mainLoop (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\core\GameServer.js:1329:15)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by Agarian** [comment]
same here, don't know why

**Comment by Andrews54757** [comment]
I think I fixed
