### ISSUE TITLE
Just happened at random...

### ISSUE THREAD

**Issue by jrgryph** [AJS-development/Ogar-unlimited#398]
TypeError: Cannot read property 'indexOf' of undefined
    at Cell.Virus.feed (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\gamemodes\Experimental.js:113:39)
    at Cell.EjectedMass.onAutoMove (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\entity\EjectedMass.js:56:9)
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\core\GameServer.js:701:15
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-collection.js:49:18
    at SortedMap.<anonymous> (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-map.js:136:25)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:590:22)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at SortedSet.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:495:27)
    at SortedMap.GenericMap.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-map.js:135:23)

Was playing for awhile before this happened.

**Comment by Andrews54757** [comment]
fixed
