### ISSUE TITLE
Error..

### ISSUE THREAD

**Issue by ortex112** [AJS-development/Ogar-unlimited#424]
When I join my server it makes that...
TypeError: Cannot read property 'length' of undefined
    at GameServer.spawnPlayer (D:\Ogar-unlimited-master\src\core\GameServer.js:871:53)
    at Mode.FFA.onPlayerSpawn (D:\Ogar-unlimited-master\src\gamemodes\FFA.js:78:16)
    at PacketHandler.setNickname (D:\Ogar-unlimited-master\src\core\PacketHandler.js:127:30)
    at PacketHandler.handleMessage (D:\Ogar-unlimited-master\src\core\PacketHandler.js:56:12)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (D:\Ogar-unlimited-master\node_modules\ws\lib\WebSocket.js:848:10)
    at D:\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:628:18
    at Receiver.applyExtensions (D:\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:371:5)
    at D:\Ogar-unlimited-master\node_modules\ws\lib\Receiver.js:604:14

**Comment by PrinceDark9243** [comment]
I think it is an of SpawnPlayer

**Comment by PrinceDark9243** [comment]
Same With Me now!

**Comment by Andrews54757** [comment]
fixed
