### ISSUE TITLE
Cannot find module 'collections/sorted-map'

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#428]
module.js:341
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Dropbox\Team PvP\src\c
ore\WorldModel.js:5:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by Andrews54757** [comment]
You must do npm install after you cd into the repo

**Comment by LegitSoulja** [comment]
Noo.. I'm updating it.. It won't manually update.. I did it for myself and it asks this. I also did that way before and it still doesn't work.

**Comment by Andrews54757** [comment]
you cannot use the update command. make package.json is there

**Comment by Dylandonute** [comment]
Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Dylandonute/Desktop/Ogar-unlimited-master/src/core/WorldModel.js:5:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by Dylandonute** [comment]
I need help

**Comment by firelightning13** [comment]
@Dylandonute #638
