### ISSUE TITLE
<r> Crash

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#429]
#Random color crash..

> TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\Administrator\Desktop\Dropbox\Shrinking FFa\src\core\GameServer.
js:1472:25
    at Array.forEach (native)
    at GameServer.mainLoop (C:\Users\Administrator\Desktop\Dropbox\Shrinking FFa
\src\core\GameServer.js:1456:27)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by Andrews54757** [comment]
fixed
