### ISSUE TITLE
Install dependencies.bat is not working and start.bat

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#432]
I try to double click Install dependencies.bat and it automatically closed and when i press start.bat it said error cannot find module

**Comment by VSabertail** [comment]
i try to run as admin and it works but then i theres an error with start.bat cannot find module

**Comment by VSabertail** [comment]
#427

**Comment by VSabertail** [comment]
@Andrews54757  @MichaelLeeHobbs @Agarian @Megabyte918 anyone pls help

**Comment by VSabertail** [comment]
SOMEONE PLEASE FIX THIS :'((((!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ShadingVaz** [comment]
Do you have Node installed?

**Comment by VSabertail** [comment]
yes
\

**Comment by VSabertail** [comment]
it worked a couple updates ago

**Comment by VSabertail** [comment]
the server worked untill the a new update

**Comment by Agarian** [comment]
try this idk if it'll work:

@echo off

set NODE_VER="5.9.1"
title ----- Install Dependencies -----


Setlocal EnableDelayedExpansion

where node /Q >nul
if %ERRORLEVEL%==1 (
    set SETUP_DIR=%CD%

    echo NodeJs is not installed on this computer...
    echo.
    echo Press any key to download NodeJs...
    pause >nul 2<&1

if not exist "%systemdrive%\Program Files (x86)" (
    start https://nodejs.org/dist/v%NODE_VER%/node-v%NODE_VER%-x86.msi
) else (
    start https://nodejs.org/dist/v%NODE_VER%/node-v%NODE_VER%-x64.msi
)

echo.
echo.
echo Please open the downloaded file and follow the instructions when it's done downloading...
echo Reopen this batch after you have installed NodeJs...
echo.
echo.
echo Press any key to exit...
pause >nul
exit

) else (

if exist "node_modules/." (
echo.
echo Dependencies already installed...
echo.
echo.

set /p update= "Do you want to update? (Y/N)"
cls
if /I "!update!"=="n" (
echo.
echo Press any key to exit...
pause >nul
exit
)
rd /s /q "node_modules/"
)

echo.
echo.
echo Clearing cache... Please wait...
call npm cache clean
cls
echo.
echo.
echo Installing dependencies, please wait...
call npm install
cls
echo.
echo.
echo Installed successfully...

cls
echo.
echo.
echo All dependencies installed successfully...
echo.
echo Press any key to exit...
pause >nul
)

**Comment by VSabertail** [comment]
where do i put it

**Comment by Agarian** [comment]
open "Install dependencies(windows).bat" , remove the original code, and paste that into it and save it.

**Comment by VSabertail** [comment]
ok

**Comment by VSabertail** [comment]
still not work

**Comment by VSabertail** [comment]
`module.js:341
     throww err;
	 ^
	 
Error: Cannot find module 'collections/sorted-map'
    at Function.module._resolveFilename (module.js:339:15)
	at Function.Module._load (module.js:290:25)
	at Module.require (module.js:367:17)
	at require (internal/module.js:16:19)
	at Object.<anonymous> (C:\Users\aaron'r/Downloads\Ogar-unlimited-master)
	at Module._compile (module.js:413:34)
	at Object.Module._extensions..js (module.js:422:10)
	at Module.load (module.js:357:32)
	at Function.Module._load (module.js:314:12)
	at Module.require (module.js:367:17)
	
Press any key to exit...`

**Comment by ItzLevvie** [comment]
npm install collections/sorted-map

**Comment by VSabertail** [comment]
ok

**Comment by VSabertail** [comment]
how do i add that

**Comment by Agarian** [comment]
in command prompt, do:

    cd 'src folder path'

then do:

    npm install

**Comment by VSabertail** [comment]
it doesent work it still sais Error cannot find module 'collections/sorted-map

**Comment by ItzLevvie** [comment]
Do ```npm install collections sorted-map```

**Comment by VSabertail** [comment]
HOWWWWWW

**Comment by VSabertail** [comment]
HOW DO I FUCKING DO THAT AND WHERE DO I DO THAT

**Comment by Megabyte918** [comment]
right click the folder with all of your server stuff in it (not src), click "open command window here" and do `npm install`

**Comment by firelightning13** [comment]
Calm down there's nothing to panic anyway

**Comment by Andrews54757** [comment]
I hope you didnt use the update command. also make sure package.json exsists

**Comment by 100ec** [comment]
I'm having the exact same problem, has VSabertail fixed it? I really want to play.

**Comment by Megabyte918** [comment]
@100ec what module did it say you were missing?

**Comment by LegitSoulja** [comment]
Make sure when installing your modules, you don't somehow already have the node_module folder.

Make sure that the directory you are running **npm install** contains package.json, and no other.

Please provide an error which was received. If your console(cmd) closes to quickly, add a **PAUSE** at the end of the batch file (Install Dependencies).

If you are missing the module is reference of collections, go to the main directory where the folder **src** and the file **package.json** and run command **npm install collections**.

**Comment by 100ec** [comment]
module.js:442
          throw err;          
I'm missing index.js, it says.

**Comment by LegitSoulja** [comment]
I won't be available non time this week, but I'm currently on my work break atm . 

Index.js isn't a module, that means you are running the installdependencies or start.bat using adminstrator which you shouldn't run as adminstrator.

**Comment by Agarian** [comment]
LOL TRY THIS https://www.khanacademy.org/computer-programming/spin-off-of-diepio/4825191326023680?width=900&&height=600

**Comment by LegitSoulja** [comment]
@Agarian ? Me? I can't sorry. I won't be in my computer non this week. I'm using my phone.

**Comment by 100ec** [comment]
I noticed that I have the node_module folder...
What should I do with it?

**Comment by Agarian** [comment]
@LegitSoulja i mean anyone

**Comment by Agarian** [comment]
Leave that alone, its required for the server to run.

**Comment by LegitSoulja** [comment]
@Agarian I can't I wont be on my computer non weeks, only on the weekends :/.

**Comment by Agarian** [comment]
i know that...

**Comment by LegitSoulja** [comment]
@Agarian and btw, I've made a game similar to agario and diep with the same concept but better but there's just this one problem I can't fix that nobody can't seem to figure out. Neither Mega, nor Natsu can figure out why what I wrote won't even work.

Whenever I figure out my problem, I can release the game ASAP, but I don't know, probably won't never happen. I got sick of trying to work with nodejs. I'm starting to hate nodejs so much.

**Comment by Agarian** [comment]
What kind of errors are you getting?

**Comment by LegitSoulja** [comment]
I'm not getting no errors lol, it's just this crap isn't working the way it supposed to and I give up on it

**Comment by Agarian** [comment]
Well whats wrong with it?

**Comment by Agarian** [comment]
idk if it'll help but you could use https://www.khanacademy.org/computer-programming/hi/4843164361162752?width=900&&height=600 as a reference

**Comment by LegitSoulja** [comment]
No, this is pointless af. I'm tired of seeing this diep, and khanacademy crap. It's not the game, it's server side problems.

It's a simple fix, but I don't know why the way I wrote it doesn't help. You're making diep with pjs, I'm not. I have already made my game but with nodejs and the server eh, pissing me off. I just quit. Might not even upload my game. Spent so much time. Wasted...

**Comment by LegitSoulja** [comment]
Sad thing about it is that nobody understands why how I made the server doesn't work. Nodejs just rekt my days, I'm like literally done with nodejs. I have no use for it, but thought it be a good use for a server, since it's small. If I don't figure out why what I wrote doesn't work I'm burning nodejs, and removing it completely and go back to pure c language, and python. It's rediculus.

**Comment by LegitSoulja** [comment]
Agitation for no reason at all. Nodejs makes me sick when things don't work they way it supposed to. 

Mainly, the thing is that, a player get a new instance of there own class(file), own settings(data) that gets sent back to the client. The thing is, when the client sends data back to the server, the server doesn't want to update the player settings, and it stays the same and never changes.

I don't understand why, but it's does. I've found no solution, other than not to use nodejs. Cause if I write something, and know how it works, but then it doesn't then I'm clueless on how it doesn't work, then I try so many things, but doesn't work at all. 

All my coding buddies, kindof hate me for even using nodejs. They don't even use nodejs. I understand strongly on why, and they won't learn it at all. I thought nodejs was good, then again nope, I disagree. Maybe node just hate me.. Well I hate it too.

**Comment by Agarian** [comment]
Can i have it the way it is now??

**Comment by LegitSoulja** [comment]
@Agarian Natsu and Mega both have it. They both looked at it, but still they don't even understand why it's not working. 

But, once you get it, and I hope you figure out why, and if you do contact me like ASAP so this weekend I can atleast finish it and have my game released. But I'm currently going to bed cause work it's tireing.

**Comment by LegitSoulja** [comment]
If they no longer have it I'll try giving it to you in the morning before I leave for work again.

**Comment by NatsuTheGreat** [comment]
I tried to do something with it right now, but the connection from host terminated. Don't know what that's supposed to be.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat change the port to 5000 in game.js

**Comment by NatsuTheGreat** [comment]
Nope :@ Didn't work. Name still won't show up.

**Comment by LegitSoulja** [comment]
I know.. The name won't set period.. I don't understand.

If you look at packet 0, which the name is being set you can see that the player name is being set. player.playerName = data.nick... Which is not working at all.. with new PlayerPacket.. 

I don't understand why its not working./

**Comment by NatsuTheGreat** [comment]
Nor do I. Could it possibly be that you never used UpdateNodes?

**Comment by LegitSoulja** [comment]
UpdateNodes is not even thing. That was actually going to be player packet but it was a weird to use update nodes.

I never heard of needing a file that doesn't exist just to create a new instance of a file.. Just forget about it because nodejs is stupid. I'll make my server using websocket sharp this weekend when I have time.

**Comment by NatsuTheGreat** [comment]
Okay.

**Comment by LegitSoulja** [comment]
:+1: :/ Bye bye nodejs. You done official made no sense to me, and been a pathetic useless 1 core use toy.

**Comment by NatsuTheGreat** [comment]
>useless 1 core use toy.

Lmfao.

**Comment by 100ec** [comment]
I still don't understand this Ogar Unlimited crap.

**Comment by LegitSoulja** [comment]
@100ec don't even waste your time.
