### ISSUE TITLE
Strict Use.. Dependency Errors

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#433]
> \src\index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by Agarian** [comment]
you need to update node, try that

**Comment by LegitSoulja** [comment]
Node is already updated

**Comment by MichaelLeeHobbs** [comment]
@LegitSoulja run node --version and paste the result here.
Also you can do this:
npm install n -g
n stable

**Comment by Andrews54757** [comment]
try the LTS version, that worked for me
