### ISSUE TITLE
plugin.js:78 fs.writeFile

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#463]
Ogar-unlimited-master\src\modules\commands\plugin.js:78
        fs.writeFile(location , body, (err, res) => {
                                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\LegitSoulja\Desktop\Ogar-unlimited-master\src\modules\CommandList.js:123:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by LegitSoulja** [comment]
Ogar-unlimited-master\src\modules\commands\reset.js:4
  let nodes = gameServer._nodes;
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\LegitSoulja\Desktop\Ogar-unlimited-master\src\modules\CommandList.js:126:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by Andrews54757** [comment]
update your nodesjs to LTS version

**Comment by LegitSoulja** [comment]
I'm using the latest. Not the LTS version. Is it a good or bad thing to have both installed?

**Comment by Andrews54757** [comment]
use the its version. same thing happened to me until i used lts

**Comment by LegitSoulja** [comment]
I still didn't work for me. I've tried lts and the current. Nightly didn't work neither
