### ISSUE TITLE
generate-object-property

### ISSUE THREAD

**Issue by Aanis12** [AJS-development/Ogar-unlimited#484]
help i am onogar unlimited-master i get the error when trying to run/start
module.js:327
    throw err;
    ^

Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Aanis\Desktop\Ogar-unlimited-master\node_mod
ules\request\node_modules\har-validator\node_modules\is-my-json-valid\index.js:1
:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Press any key to exit...

i tried npm install

**Comment by Aanis12** [comment]
nvm i reinstalled ogar ultimate and rerun npm and it worked

**Comment by Agarian** [comment]
also its `ogar unlimited` xD

**Comment by Megabyte918** [comment]
lol
