### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by RaptorFX** [AJS-development/Ogar-unlimited#485]
I tried the new version.I installed dependecies [Windows] again and got problem :  module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\KRASKO\Desktop\Agar\Ogar-unlimited-master\node_modules\minimatch\minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit... 
Please help!

**Comment by LegitSoulja** [comment]
Don't use the latest version of node. Recommended to install v5.9.0

**Comment by LegitSoulja** [comment]
And try running npm-intall brace-expansion where the folder node_modules is located

**Comment by RaptorFX** [comment]
I got   v5.9.1.Thx i will try

**Comment by LegitSoulja** [comment]
Your welcome
