### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by maciej441** [AJS-development/Ogar-unlimited#499]
After launching Start.bat this thing is showed.

module.js:440
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Maciej\Desktop\Ogar-unlimited-master\node_modules\request\node_modules\readable-stream\lib\_stream_duplex.js:21:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

P.S. Jester skin from april fools day isn't working.

**Comment by Megabyte918** [comment]
do `npm install process-nextick-args`

**Comment by maciej441** [comment]
I don't think they removed it from client, because I saw someone with this skin.

**Comment by maciej441** [comment]
"npm install process-nextick-args" isn't working. It's showing the same thing

**Comment by Andrews54757** [comment]
do `npm install request`

**Comment by Megabyte918** [comment]
@maciej441 really? I went to agar.io and checked the skins and I couldn't fid it anywhere

**Comment by Agarian** [comment]
it was an april fools special.

**Comment by maciej441** [comment]
@Andrews54757 it isn't working. it's this thing now

TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (C:\Users\Maciej\Desktop\Ogar-unlimited-master\src\core\GameServer.js:1453:9)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)


@Megabyte918 @Agarian  it was avaibe for buy only on april fools, but when you buy this you can use it forever. Btw. I saw someone with this skin yesterday.

**Comment by firelightning13** [comment]
@maciej441 What kind of NodeJS version are you using?

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/508

**Comment by Agarian** [comment]
@maciej441 you're the third person to report this error, I am not sure why this error exists (mainly because i don't get that error)

**Comment by Andrews54757** [comment]
i think its just an old nodejs

**Comment by maciej441** [comment]
@Andrews54757 I've got nodejs 6.0.0

**Comment by firelightning13** [comment]
We should have put the important note in README.md to downgrade version to 5.9.0

**Comment by Agarian** [comment]
That's probably the problem.

**Comment by maciej441** [comment]
can someone give me the link to 5.9.0
?

**Comment by maciej441** [comment]
it's now working. thanks

**Comment by LPArigma** [comment]
@maciej441 Nodejs LTS v4.4.2 works as well

**Comment by hassanila97** [comment]
But why would you force us to downgrade.. I dont appreciate that.. I know its a module conflicting   but are there more info to know?
