### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#517]
module.js:440
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\tommy\Desktop\Ogar-unlimited-master\src\node_modules\request\node_modules\readable-stream\lib\_stream_duplex.js:21:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...

**Comment by LegitSoulja** [comment]
[Duplicated Post.](https://github.com/AJS-development/Ogar-unlimited/issues/508)

issue closed.

**Comment by LegitSoulja** [comment]
@tommyb008 If that does not work let me know

**Comment by Agarian** [comment]
i need help with connections in my agar client. it doesnt seem to allow any connections.

connect("ws://127.0.0.1:443")
main_out.js?542:168 Connecting to ws://127.0.0.1:443
undefined
main_out.js?542:191 socket open
main_out.js?542:204 socket close

here is the client: 
https://cdn.discordapp.com/attachments/171340096694517760/177943184096100354/agarclone.zip

**Comment by LegitSoulja** [comment]
You need to grab the new packet nodes, and the new protocol.
