### ISSUE TITLE
Please help NOT DUPLICATED

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#518]
THIS IS NOT DUPLICATED his said call back 

module.js:440
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\tommy\Desktop\Ogar-unlimited-master\src\node_modules\request\node_modules\readable-stream\lib\_stream_duplex.js:21:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...

http://imgur.com/88Snw5s

and i cant put any commands in either

**Comment by tommyb008** [comment]
i found no help at all from the "DUPLICATE post you sent me"

**Comment by LegitSoulja** [comment]
You didnt have to create a new issue..

run this command in the ogar ./src outside directory

> npm install request

**Comment by tommyb008** [comment]
whats the difference from npm install?

**Comment by LegitSoulja** [comment]
@tommyb008 npm install installs all the packages. Be more specific with the package using the command i gave you above.

**Comment by LegitSoulja** [comment]
@tommyb008 If that still doesnt work, you can replace your node_modules folder with this one
https://github.com/AJS-development/nodemodules

**Comment by LegitSoulja** [comment]
@tommyb008 Also due to the new Agar.io update. Your not allowed to connect the server to the client. We are working on a fix that allows us to connect back. It may be a while before you can actually use the servers agains. Say thank to miniclip for messing up everything.
