### ISSUE TITLE
module.js:440     throw err;     ^  Error: Cannot find module 'json-schema'     at Function.Module._resolveFilename (module.js:438:15)     at Function.Module._load (module.js:386:25)     at Module.require (module.js:466:17)     at require (internal/module.js:20:19)     at Object.<anonymous> (C:\Users\Home Use\Desktop\Ogar-unlimited-master\node_ modules\request\node_modules\http-signature\node_modules\jsprim\lib\jsprim.js:10 :22)     at Module._compile (module.js:541:32)     at Object.Module._extensions..js (module.js:550:10)     at Module.load (module.js:456:32)     at tryModuleLoad (module.js:415:12)     at Function.Module._load (module.js:407:3)  Press any key to exit...

### ISSUE THREAD

**Issue by Ckicky** [AJS-development/Ogar-unlimited#563]

**Comment by firelightning13** [comment]
Can you not do that at title?!?

**Comment by Andrews54757** [comment]
`npm install request`

**Comment by Megabyte918** [comment]
the amount of issues request causes is starting to get annoying...

**Comment by Andrews54757** [comment]
@Ckicky  see #548 . one more time, you get banned for a month
