### ISSUE TITLE
Crashes on split.

### ISSUE THREAD

**Issue by aaxxo** [AJS-development/Ogar-unlimited#57]
Hi there, first of very nice work on this server.  The new config values are very nice.   However I every time I begin to split it crashes.  Here is the error in the console.

```
TypeError: Object #<Object> has no method 'log10'
    at GameServer.splitCells (/home/aaxxo/agario/Ogar/src/GameServer.js:734:65)
    at Mode.pressSpace (/home/aaxxo/agario/Ogar/src/gamemodes/Mode.js:273:20)
    at PlayerTracker.update (/home/aaxxo/agario/Ogar/src/PlayerTracker.js:103:34)
    at GameServer.updateClients (/home/aaxxo/agario/Ogar/src/GameServer.js:530:39)
    at GameServer.mainLoop (/home/aaxxo/agario/Ogar/src/GameServer.js:479:14)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by aaxxo** [comment]
Opened a pull request with fix.  

https://github.com/AJS-development/Ogar-unlimited/pull/58
