### ISSUE TITLE
I need help with an all too common error

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#592]
RangeError: Maximum call stack size exceeded
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:582:34)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)
    at Node.reduce (/home/ubuntu/workspace/node_modules/collections/sorted-set.js:587:27)

**This happens EVERY TIME if I use the reset command and try to respawn.**
**Can i remove this error? (The answer is probably no =\ )**

**Comment by darknight99x** [comment]
Strange. I use the reset command alot and never see this problem.

Sounds to me that your virtual environment (private server) doesn't have enough memory or CPU power to handle the reset.

If that's not, something might be wrong with your server's files.

**Comment by Agarian** [comment]
i think i fixed it.

**Comment by darknight99x** [comment]
@Agarian can we have the solution incase someone else has this problem

**Comment by Agarian** [comment]
i went to the file:
> node_modules/collections/sorted-set.js

and changed

    "use-strict";

to 

    'use-strict';

**Comment by Megabyte918** [comment]
lolwut
