### ISSUE TITLE
i did the update all command and now its broke

### ISSUE THREAD

**Issue by iIronicGameryt** [AJS-development/Ogar-unlimited#595]
now i get this when i do update all 
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.5.5
[Client] Listening on *:8080
Error: listen EACCES 0.0.0.0:88
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at StatServer.start (/home/ubuntu/workspace/src/core/StatServer.js:29:21)
    at GameServer.start (/home/ubuntu/workspace/src/core/GameServer.js:454:21)
    at ControlServer.start (/home/ubuntu/workspace/src/core/ControlServer.js:57:21)
    at Object.<anonymous> (/home/ubuntu/workspace/src/index.js:39:26)
    at Module._compile (module.js:409:26)
[Error] Please make sure you are running Ogar with root privileges.
OgarUnlimited terminated with code: 1

**Comment by Agarian** [comment]
EACCES means you have permissions issue, but I've never had this error so IDK much about it besides the fact it has to do with permissions problems.

**Comment by iIronicGameryt** [comment]
fixed

**Comment by darknight99x** [comment]
@Agarian he had another instance of the server running, already using that port.

**Comment by iIronicGameryt** [comment]
hmm the tournament still doesnt work still can move in it

**Comment by Agarian** [comment]
the server's way of saying a port is already in use is an EADDERNUISE error.

**Comment by iIronicGameryt** [comment]
yes i fixed that but i cant move in tournament mode after the count down your just stood there for the who;e game

**Comment by Agarian** [comment]
oh nvm it not fixed yet xD

**Comment by iIronicGameryt** [comment]
ugh xD

**Comment by Agarian** [comment]
andrews said he'd fix it so try and wait? lol

**Comment by iIronicGameryt** [comment]
ye :)
