### ISSUE TITLE
start.ini dont open correctly

### ISSUE THREAD

**Issue by ghostangel2212** [AJS-development/Ogar-unlimited#615]
module.js:440
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Gmobil_Shop\Desktop\Ogar-unlimited-master\node_modules\bl\node_modules\readable-stream\lib\_stream_duplex.js:21:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...

I do npm install 

i have node.js 6.1.0 

# SORRY FOR BAD ENGLISH

**Comment by Andrews54757** [comment]
STOP DUPLICATING THIS ISSUE PLEASE. IF I SEE ANOTHER ONE, I WILL BAN! (see #614 )

**Comment by Megabyte918** [comment]
He's new here

**Comment by Megabyte918** [comment]
Maybe we should just create an issue that explains what to do when missing different node modules so people will stop asking

**Comment by ghostangel2212** [comment]
i fix it hehehe was easy, thanks to all who try to help me

**Comment by firelightning13** [comment]
@Megabyte918 Agreed. @Andrews54757 You should probably do "Troubleshooting Guide".
