### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#626]
i installed SuperMinions plugin and when i launch tha server : fafad:~/workspace/src $ sudo node index.js
/home/ubuntu/workspace/src/oldindex.js:49
});
 ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/src/index.js:25:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
 need help :(

**Comment by Megabyte918** [comment]
lolwut

**Comment by LegitSoulja** [comment]
@bangana strike 1 for not following the guidelines and not provided enough information.

**Comment by Andrews54757** [comment]
@LegitSoulja Not really as he closed it

**Comment by Andrews54757** [comment]
was probably an accident
