### ISSUE TITLE
Troubleshooting Guide

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#638]
# What to do when missing node modules & stuff
Hey guys, I'm going to be showing how to solve different errors whilst starting OgarUL. I've been seeing a lot of issues regarding missing modules lately, so I went through those issues (and some old ones) and I gathered those errors and put them in here, along with the fix.
If any of the errors are missing, or i got something wrong, @AJS-development/ogar-unlimited-devs feel free to edit this comment :D

### Error: Cannot find module '.core/_(Insert module here)_'
redo the `update` command
or download the OgarUL zip from GitHub and replace the missing files
found in #638, #697, and #502
### Error: Cannot find module 'async'
do `npm install async`
found in #638
### Error: Cannot find module 'collections'
do `npm install collections/sorted-map`
found in #614
### Error: Cannot find module 'process-nextick-args'
do `npm install request`
found in #517, #508, #518, #428, #499, and #466 
### Error: Cannot find module 'brace-expansion'
`npm install brace-expansion -g` or `npm install minimatch`
*_or just use node version 5.9.0_
found on #502 and #485
### Error: Cannot find module 'request'
do `npm install request`
found in #307 
### SyntaxError: Use of const in strict mode.
downgrade to node version _5.9.0_
found in #638
### TypeError: "callback" argument must be a function
downgrade to node version _5.9.0_
found in #642
### Blank white/grid screen when using client
make sure everything is updated, your using _chrome_, and you have the latest client.
or just use play.ogarul.tk
or OR refer to https://github.com/AJS-development/Ogar-unlimited/issues/638#issuecomment-220816552
found in #591, #625, #580, #623, #624, #613, and #628 (jeez that's a lot o.o)
### Error: Cannot find module 'inflight'
do `npm install inflight`
found in #638
.
.
.
If you are still having issues, downgrade to node version 5.9.0 
If you are STILL having issues, use this: https://github.com/AJS-development/Pre-Installed-ogarUL
And if you are STILL STILL having issues, uninstall the current node from your computer, download the Pre-Installed OgarUL, then reinstall it. (works for me at least :P)

**Comment by GOpb** [comment]
Help i am still getting blank screen nothing is loading

**Comment by Andrews54757** [comment]
1. Update your server
2. Play using play.ogarul.tk

**Comment by GOpb** [comment]
i did it fixed nothing

**Comment by GOpb** [comment]
i entered the update command into the console and i tried to join my server and it did not work

**Comment by GOpb** [comment]
please help

**Comment by Andrews54757** [comment]
i hope your using chrome

**Comment by Andrews54757** [comment]
somehow it only works on chrome

**Comment by GOpb** [comment]
ok got it working how do i find my player ID

**Comment by Andrews54757** [comment]
playerlist

**Comment by Martinali12** [comment]
![sni](https://cloud.githubusercontent.com/assets/17472593/15364077/c25855a8-1d23-11e6-9cb7-c5ab0809cd18.PNG)
 I have this problem anyway to fix

**Comment by Megabyte918** [comment]
@Martinali12 what node version?

**Comment by LegitSoulja** [comment]
Obviously he's too high. Downgrade your node to 5.9.0

**Comment by Martinali12** [comment]
how to downgrade on koding

**Comment by LegitSoulja** [comment]
uninstall it..

**Comment by paulo364gamer** [comment]
I do not know if I'm in the right place, but the skin works in http://play.ogarul.tk/?

**Comment by Megabyte918** [comment]
@paulo364gamer nope

**Comment by fayizan** [comment]
New Error...,Just  used updated all command
![screenshot_4](https://cloud.githubusercontent.com/assets/19163419/15452136/6e4ab6d2-2001-11e6-8d83-b1f7e0f9c035.jpg)

**Comment by LegitSoulja** [comment]
@fayizan just download the zip from github and place the missing files

**Comment by firelightning13** [comment]
@Megabyte918 add this to "Blank white/grid screen when using client":
If you run in https://ajs-development.github.io/client/ , make sure to click "Load unsafe scripts" from the "shield" icon at the top right corner of your Chrome browser.

![image](https://cloud.githubusercontent.com/assets/17120382/15452597/aba54c7e-2027-11e6-8457-844e412b0552.png)

**Comment by bean07** [comment]
I can't spawn out,its socket open but when i try to spawn its can't spawn i tried on ogarul client and agarioclient too!

**Comment by bean07** [comment]
at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js
some thing happend like this

**Comment by fayizan** [comment]
Solution to this error:
![screenshot_4](https://cloud.githubusercontent.com/assets/19163419/15454190/ac6a31de-204e-11e6-97a8-ffc071d3ea6e.jpg)

Paste this below file into **src\core** folder
[Multiverse.js](https://drive.google.com/file/d/0BxRUPVJOvbqkRFFOSEhmWXJGbjg/view?usp=sharing)

But I recommend you to follow @LegitSoulja comment that you can find above

**Comment by fayizan** [comment]
@bean07 I think the admin configuration is buggy I too get the same error but I solved, just change the `adminConfig = 0` in the config.ini

**Comment by tg170** [comment]
help
![troubleshooting guide issue 638 ajs-development_ogar-unlimited](https://cloud.githubusercontent.com/assets/18076173/15454290/861c5920-202c-11e6-8786-8059f89d2c84.png)

**Comment by ItzLevvie** [comment]
Do ```npm install async```

**Comment by tg170** [comment]
how when i press any key it closes

**Comment by tg170** [comment]
NM

**Comment by tg170** [comment]
THX

**Comment by Megabyte918** [comment]
cleaned comments and added some previous errors from here

**Comment by RevivedSol** [comment]
theres a new bug. It says something like inflight

**Comment by firelightning13** [comment]
@RevivedSol do `npm install inflight` or do `npm install again`

**Comment by Megabyte918** [comment]
@RevivedSol do you remember what it said? so i can insert it

**Comment by firelightning13** [comment]
@Megabyte918 
Error: Cannot find module 'inflight'

**Comment by RevivedSol** [comment]
theres a new one again  cannot find module once   but i tried doing   npm install once   and guess what it works

**Comment by rayer1011** [comment]
Can't use default Skins anymore.
ex: when I try to use the name "8" ,however, there's no 8-ball skin being showed.

**Comment by LegitSoulja** [comment]
@rayer101 I think you need to add the skins yourself if you are hosting your own client.

**Comment by rayer1011** [comment]
@LegitSoulja it worked!Thanks for your reply. :D

**Comment by ViinKz** [comment]
[INFO] Loading Config Files...
[INFO] Loading ./settings/advConfig.ini
[INFO] Loading ./settings/config.ini
[INFO] Loading ./settings/override.ini
[INFO] Your unique id is: he0xdRRj0f
[INFO] Loading plugins
[INFO] Starting ConsoleService
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.0.1
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1

Press any key to exit...
what do i do???

**Comment by Megabyte918** [comment]
try sudo?

**Comment by FireFoxYT** [comment]
My module says 

module.js:341
    throw err;
    ^

Error: Cannot find module './DataPacket'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\trist\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\packet\index.js:10:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

What do i do

**Comment by LegitSoulja** [comment]
@FireFoxYT re-download Ogar-unlimited zip. 
Get the file **DataPacket.js** from the zip in the folder **packet** and extra it to ./packet in your game directory.

**Comment by bean07** [comment]
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

Press any key to exit...
why my module can't install i check and i have this error
npm WARN EPACKAGEJSON Ogar_Unlimited@17.0.0 license should be a valid SPDX license expression

**Comment by LegitSoulja** [comment]
@bean07 don't run as administrator

**Comment by LegitSoulja** [comment]
And also cd to your game directory, or use the batch files to install dependencies and start the server

**Comment by Agarian** [comment]
Just run start.bat

**Comment by Agarian** [comment]
Will close and re-open in a new issue.
