### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lbniese** [AJS-development/Ogar-unlimited#65]
Hi,

I'm currently using this commit: https://github.com/AJS-development/Ogar-unlimited/commit/49e4e64af3ed02920dec6b6999050c6ad6fb2877

I changed the gamemode to id 18 (leap gamemode) and upon leaping into one of the red object the game crashed/froze as seen in the below image:
![Image of freeze](http://i.imgur.com/Zd2UEqY.jpg)

Console log error:
```
 >TypeError: Cannot call method 'indexOf' of undefined
    at Cell.MotherCell.onRemove (/home/Ogar-unlimited/src/entity/MotherCell.js:143:49)
    at GameServer.removeNode (/home/Ogar-unlimited/src/GameServer.js:614:10)
    at GameServer.updateMoveEngine (/home/Ogar-unlimited/src/GameServer.js:886:18)
    at GameServer.cellTick (/home/Ogar-unlimited/src/GameServer.js:630:10)
    at GameServer.mainLoop (/home/Ogar-unlimited/src/GameServer.js:667:29)
    at wrapper [as _onTimeout] (timers.js:270:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

**Comment by Lbniese** [comment]
As far as I can tell the red objects shouldn't be in the leap gamemode, but not all of the red object despawned when I changed gamemode from Experimental (id 2) to Leap (id 18).

**Comment by Andrews54757** [comment]
Of course, the gamemode command is not really completed, it says so in regular ogar as well. to change your gamemode you have to edit gameserver.ini (config file).
