### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by bean07** [AJS-development/Ogar-unlimited#690]
/home/bean07/Ogar-unlimited/src/index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
whats this error guys!

**Comment by firelightning13** [comment]
#638

**Comment by bean07** [comment]
tks,fixed!
