### ISSUE TITLE
Help me again pls!

### ISSUE THREAD

**Issue by bean07** [AJS-development/Ogar-unlimited#696]
at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (/home/bean07/Ogar-Unlimited/src/core/GameServer.js:938:20)
    at Mode.FFA.onPlayerSpawn (/home/bean07/Ogar-Unlimited/src/gamemodes/FFA.js:78:16)
    at MinionPlayer.<anonymous> (/home/bean07/Ogar-Unlimited/src/ai/MinionPlayer.js:81:32)
:( its show when i connect to server and server reponse socket open i can't spawn and i see terminal i see this

**Comment by Martinali12** [comment]
Wtf reinstall

**Comment by firelightning13** [comment]
.

**Comment by Ckicky** [comment]
...

**Comment by LegitSoulja** [comment]
@bean07 

The reason why im not helping you is because you provided less, to no information at all instead of a repeating stacktrace. Please edit this correctly, provided full beginning and part of this stacktrace from your log. 

Check out for these things.
- Node v5.9.1 < or less
- IF Agar.io Client (ClientVerstion = 0, PacketVersion = 0, **./settings/advConfig.ini**)
- Updated OgarUl to the latest version (**update all**)

**Comment by bean07** [comment]
thx,the problem because i set adminconfig=1! -_-
