### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by iMaleKz** [AJS-development/Ogar-unlimited#697]
when i open the server 
i got the new update 
i type
update all
but after that 
i got 
module.js:341
    throw err;
    ^

Error: Cannot find module './core/Multiverse'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\MAX\Desktop\Ogar-unlimited-master\src\index.js:5:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

Press any key to exit...

**Comment by Martinali12** [comment]
change port :P

**Comment by iMaleKz** [comment]
any port ?

**Comment by firelightning13** [comment]
@iMaleKz It's the missing file. All you gonna do is:

Re-download the file then npm install.... done

**Comment by iMaleKz** [comment]
i'm newbie
please I want a detailed explanation

**Comment by tg170** [comment]
same problem 
how to download and install this npm file

**Comment by fayizan** [comment]
#638

**Comment by LegitSoulja** [comment]
@iMaleKz Lol these comments and stupid.. 

You update command failed to install the new update of OgarUl. You need to download the zip of OgarUl here on github and replace the missing files.

**Comment by Andrews54757** [comment]
Sorry, I forgot to include it in files.jsion
