### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by firelightning13** [AJS-development/Ogar-unlimited#71]
```
C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\gamemodes\Experimental.js:24
        var mapSize = gameServer.config.borderLeft + gameServer.config.borderRight +
                      ^

ReferenceError: gameServer is not defined
    at Mode.Experimental (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\gamemodes\Experimental.js:24:23)
    at Object.get (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\gamemodes\index.js:34:20)
    at new GameServer (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\GameServer.js:156:30)
    at Object.<anonymous> (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\index.js:32:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
```
This happens when I change gamemode experimental

**Comment by Andrews54757** [comment]
I fixed it
