### ISSUE TITLE
rainbow gamemode no longer works

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#728]
TypeError: Cannot assign to read only property 'rainbow' of 2720
    at Mode.Rainbow.changeColor (/home/ubuntu/workspace/src/gamemodes/Rainbow.js:145:18)
    at Mode.Rainbow.onTick (/home/ubuntu/workspace/src/gamemodes/Rainbow.js:181:10)
    at GameServer.gameModeTick (/home/ubuntu/workspace/src/core/GameServer.js:1676:21)
    at GameServer.<anonymous> (/home/ubuntu/workspace/src/core/GameServer.js:1523:37)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Megabyte918** [comment]
did the recent update fix it?

**Comment by Andrews54757** [comment]
i will look into this
