### ISSUE TITLE
[Bug] TimedFFA and HungerGames time reset problem

### ISSUE THREAD

**Issue by xMuratY** [AJS-development/Ogar-unlimited#737]
Game ending but dont resetting for hungergames and timedffa problem is ı changing time 10second but dont changing time and dont resetting server

`>TypeError: gameServer.startingFood is not a function
    at Mode.Tournament.updateLB (/root/Ogar-unlimited/src/gamemodes/Tournament.js:229:20)
    at GameServer.mainLoop (/root/Ogar-unlimited/src/core/GameServer.js:1617:23)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: gameServer.startingFood is not a function
    at Mode.Tournament.updateLB (/root/Ogar-unlimited/src/gamemodes/Tournament.js:229:20)
    at GameServer.mainLoop (/root/Ogar-unlimited/src/core/GameServer.js:1617:23)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: gameServer.startingFood is not a function
    at Mode.Tournament.updateLB (/root/Ogar-unlimited/src/gamemodes/Tournament.js:229:20)
    at GameServer.mainLoop (/root/Ogar-unlimited/src/core/GameServer.js:1617:23)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: gameServer.startingFood is not a function
    at Mode.Tournament.updateLB (/root/Ogar-unlimited/src/gamemodes/Tournament.js:229:20)
    at GameServer.mainLoop (/root/Ogar-unlimited/src/core/GameServer.js:1617:23)
    at Timer.listOnTimeout (timers.js:92:15)`

**Comment by Andrews54757** [comment]
I think i fixed
