### ISSUE TITLE
My ogar says TypeError: "callback" argument must be a function

### ISSUE THREAD

**Issue by HazardYT** [AJS-development/Ogar-unlimited#743]
When i launch ogar with skype closed it says this

TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (C:\Users\JoshuaTurbessi\Desktop\Ogar-unlimited-822c54a5bf03d7004706e8d43f30919edd48ca5b\src\core\GameServer.js:1546:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

and i installed dependancies

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/638
