### ISSUE TITLE
[VPS] VPS Vs Index.js

### ISSUE THREAD

**Issue by l3mpik** [AJS-development/Ogar-unlimited#749]
I decided to do the server, only a small problem as follows:

**Ubuntu 14.04
Node version: 0.10.25
Problem:**

const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

I tried to remove StrictMode but it did not work. Anyone have any idea? Thanks for any help :)

**Comment by LegitSoulja** [comment]
Update node to 5.9.0
