### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by awikwee** [AJS-development/Ogar-unlimited#756]
I got something that says what i will show after trying the latest one

module.js:341
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Alex\Desktop\Ogar-unlimited-16.5.7\Ogar-unli
mited-16.5.7\node_modules\bl\node_modules\readable-stream\lib\_stream_duplex.js:
21:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...
 Please help me

**Comment by systemroot** [comment]
what is your OS ?!
Have you try to use "npm install" on folder "Ogar-Unlimited" or in folder "Ogar-Unlimited/src" 
?

**Comment by xMuratY** [comment]
dont open issue check issues or search in issues

use npm install request

**Comment by David1ali12** [comment]
noob kids

**Comment by Parth1999** [comment]
do cd "Ogar- Unlimited-Directory" without " " in cmd
then do "npm install" wait till it completes.
do "cd src"
then "node index.js" and you server should start :)

**Comment by Megabyte918** [comment]
#638!!
