### ISSUE TITLE
Error while running the start.bat

### ISSUE THREAD

**Issue by arnab-banerjee** [AJS-development/Ogar-unlimited#757]
const Readline = require('readline');
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Press any key to exit...

**Comment by RasyiidWho** [comment]
downgrade to node version 5.0.9 #638

**Comment by David1ali12** [comment]
^^

**Comment by Agarian** [comment]
5.9.0!
