### ISSUE TITLE
Agario server 16.7.8 connection error

### ISSUE THREAD

**Issue by agariobro12** [AJS-development/Ogar-unlimited#762]
Hey i have a problem i have updatet my server to 16.7.8 and i will connect and i can´t connect

Garbage collecting in 1440 minutes!
TypeError: this.gameServer.getNodesPlayer(...).some is not a function
    at GeneratorService.virusCheck (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)
\lel\src\core\GeneratorService.js:83:55)
    at GeneratorService.update (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel
\src\core\GeneratorService.js:61:10)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: this.getWorld(...).getPlayerNodes(...).forEach is not a function
    at GameServer.updateCells (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\
src\core\GameServer.js:794:38)
    at GameServer.cellUpdateTick (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\l
el\src\core\GameServer.js:1521:10)
    at GameServer.mainLoop (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src
\core\GameServer.js:1543:23)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
>TypeError: nodes.sorted is not a function
    at GameServer.updateMoveEngine (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)
\lel\src\core\GameServer.js:744:11)
    at GameServer.cellTick (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src
\core\GameServer.js:1699:10)
    at GameServer.<anonymous> (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\
src\core\GameServer.js:1534:37)
    at Timer.listOnTimeout (timers.js:92:15)
    at listOnTimeoutNT (timers.js:118:19)
    at _combinedTickCallback (node.js:374:13)
    at process._tickCallback (node.js:401:11)

**Comment by agariobro12** [comment]
NewBug===


TypeError: this.gameServer.getNodesPlayer(...).some is not a function
    at GeneratorService.virusCheck (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src\core\GeneratorService.js:79:55)
    at GeneratorService.update (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src\core\GeneratorService.js:57:10)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: nodes.sorted is not a function
    at GameServer.updateMoveEngine (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src\core\GameServer.js:695:11)
    at GameServer.cellTick (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src\core\GameServer.js:1614:10)
    at GameServer.mainLoop (C:\Users\Gamer-Acer\Desktop\Neuer Ordner (2)\lel\src\core\GameServer.js:1449:25)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by agariobro12** [comment]
Help please :(

**Comment by DarkZYT** [comment]
reinstall your private server

**Comment by agariobro12** [comment]
why can not fix this? :( also deinstall update

**Comment by agariobro12** [comment]
ok i restall it
:-1:

**Comment by xMuratY** [comment]
Remove and reinstall server

Or make update all again and remove node_modules folder 

npm install
npm install ws
npm install request

**Comment by agariobro12** [comment]
Ok

**Comment by agariobro12** [comment]
dont working i have this error agin

**Comment by agariobro12** [comment]
also reinstall

**Comment by agariobro12** [comment]
new error after reinstall -,-  cant find module collections/sorted-map i have installed sorted-map per npm and i will install collections/sorted-map dont working

**Comment by agariobro12** [comment]
AHHHHHHH after 3houers have i patched this my brother has edited the advconfig :-1:  Thanks on all guys helped me :)
