### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by PabloAran** [AJS-development/Ogar-unlimited#805]
1- help?

module.js:341
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (I:\Users\Pablo\ENGICAN\a\Ogar-unlimited-master\node_modules\bl\node_modules\readable-stream\lib\_stream_duplex.js:21:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

2- why skins doesnt work?

**Comment by Tokoagar** [comment]
Skins are not added for now wait the owner is working on it

**Comment by David1ali12** [comment]
1. `npm install process-nextick-args` 
first of all open cmd 
- open cmd  type cd location of ogarulimited example cd `Downloads`
- `cd Ogar-unlimited` 
- `npm install process-nextick-args`

2. they will very soon

**Comment by Megabyte918** [comment]
#638
