### ISSUE TITLE
TypeError Cannot read property 'IndexOf' error

### ISSUE THREAD

**Issue by jrgryph** [AJS-development/Ogar-unlimited#854]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
experimental
What version are you on?
17.0.1
What command did you type if any?
n/a
You must have a description as well
TypeError: Cannot read property 'indexOf' of undefined
    at Cell.Virus.feed (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\gamemodes\Experimental.js:101:40)
    at Cell.EjectedMass.onAutoMove (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\entity\EjectedMass.js:59:9)
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\core\GameServer.js:759:15
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-collection.js:49:18
    at SortedMap.<anonymous> (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-map.js:136:25)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:590:22)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
TypeError: Cannot read property 'indexOf' of undefined
    at Cell.Virus.feed (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\gamemodes\Experimental.js:101:40)
    at Cell.EjectedMass.onAutoMove (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\entity\EjectedMass.js:59:9)
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\core\GameServer.js:759:15
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-collection.js:49:18
    at SortedMap.<anonymous> (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-map.js:136:25)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:590:22)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:587:27)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:587:27)
    at SortedSet.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:495:27)
    at SortedMap.GenericMap.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-map.js:135:23)
TypeError: Cannot read property 'indexOf' of undefined
    at Cell.Virus.feed (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\gamemodes\Experimental.js:101:40)
    at Cell.EjectedMass.onAutoMove (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\entity\EjectedMass.js:59:9)
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\src\core\GameServer.js:759:15
    at C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-collection.js:49:18
    at SortedMap.<anonymous> (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\generic-map.js:136:25)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:590:22)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:587:27)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
    at Node.reduce (C:\Users\John\Desktop\Games\agario\Ogar-unlimited\node_modules\collections\sorted-set.js:593:28)
It doesn't crash and is still playable.
Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by Megabyte918** [comment]
try getting rid of the underscore in line 101 of Experimental.js (cant test for myself :P)

**Comment by Andrews54757** [comment]
fixed

**Comment by jrgryph** [comment]
Thanks!
