### ISSUE TITLE
Async Error

### ISSUE THREAD

**Issue by notblade02** [AJS-development/Ogar-unlimited#873]
when I click on the file "start" this giveme  a error :

module.js:329
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\Notblade\Desktop\Ogar-unlimited-master\src\c
ore\Updater.js:5:15)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)

Press any key to exit...

**Comment by notblade02** [comment]
Someone can please help me?

**Comment by Andrews54757** [comment]
do `npm install async`

**Comment by notblade02** [comment]
IT DONT WORK

**Comment by notblade02** [comment]
I already DID THAT

**Comment by Agarian** [comment]
run the file "Install dependencies(windows)" in the src folder
