### ISSUE TITLE
Start Module

### ISSUE THREAD

**Issue by FireFoxYT** [AJS-development/Ogar-unlimited#905]
My start module is saying 

module.js:341
    throw err;
    ^

Error: Cannot find module './DataPacket'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\trist\Desktop\Ogar-unlimited-master\Ogar-unlimited-master\src\packet\index.js:10:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

How do i fix this I have reinstalled node already. 
What do I do?

**Comment by Agarian** [comment]
Redownload ogarul
