### ISSUE TITLE
Uhh, a start error

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#91]
C:\Users\Lucas\Desktop\Ogar-unlimited-master\src>node index.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Lucas\Desktop\Ogar-unlimited-master\src\modules\CommandList.js:7:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

C:\Users\Lucas\Desktop\Ogar-unlimited-master\src>if errorlevel 1 (if not errorlevel 3 (GOTO END; ) )

C:\Users\Lucas\Desktop\Ogar-unlimited-master\src>pause

**Comment by Lukkez** [comment]
I discovered the error

**Comment by Agarian** [comment]
redo npm install

**Comment by Andrews54757** [comment]
1. go cd into src
2. do npm install

or do npm install request
