### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by Jassim11** [AJS-development/Ogar-unlimited#912]
when i run start.bat i get this error
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (C:\Users\Dream_000\Desktop\New folder\Ogar-unlimited-master\src\core\GameServer.js:1528:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

idk if its the reason im getting white screen on http://play.ogarul.tk/

**Comment by LegitSoulja** [comment]
@Jassim11 what version node are you running?

**Comment by Jassim11** [comment]
v6.2.1

**Comment by Jassim11** [comment]
@LegitSoulja

**Comment by LegitSoulja** [comment]
@Jassim11 please downgrade to v5.9.0. Thanks
