### ISSUE TITLE
error? #2

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#915]
_ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.0.1
Error: listen EADDRINUSE :::88
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at StatServer.start (/root/ogar/new/Ogar-unlimited/src/core/StatServer.js:29                                 :21)
    at GameServer.start (/root/ogar/new/Ogar-unlimited/src/core/GameServer.js:49                                 8:21)
    at ControlServer.start (/root/ogar/new/Ogar-unlimited/src/core/ControlServer                                 .js:62:21)
    at Multiverse.create (/root/ogar/new/Ogar-unlimited/src/core/Multiverse.js:8                                 6:7)
    at Multiverse.init (/root/ogar/new/Ogar-unlimited/src/core/Multiverse.js:141                                 :26)
[Error] Server could not bind to port! Please close out of Skype or change 'serv                                 erPort' in gameserver.ini to a different number.
[INFO] OgarUnlimited terminated with code: 1
[root@vps81601 src]#

**Comment by Andrews54757** [comment]
Look up other issues
