### ISSUE TITLE
How to fix this issue i'm on mac so bear with me

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#920]
So how do i fix this?

bash-3.2# sudo node index.js
/Users/leithmoore/Desktop/Ogar-unlimited/src/index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I Have ran npm install in the src folder with sudo -s 

please help

**Comment by Andrews54757** [comment]
do `node -v` and if the result is not 5.9.0, do `sudo npm install n -g` then do `sudo n 5.9.0` and reload your terminal
