### ISSUE TITLE
Start.bat not working

### ISSUE THREAD

**Issue by pleashehelpz** [AJS-development/Ogar-unlimited#979]
I instaled npm and all things but this keeps popping up

C:\Users\ACOOLPERSON\Desktop\Ogar-unlimited-master\src\index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Press any key to exit...

please help

**Comment by noodlychezzy** [comment]
You will need to have the latest version of node.js

you can get it from here:

https://nodejs.org/dist/v4.4.5/node-v4.4.5-x86.msi

**Comment by Agarian** [comment]
NOOO YOU MUST HAVE NODE V5.9.0!

**Comment by firelightning13** [comment]
bruh why v4.4.5

**Comment by Agarian** [comment]
IKR

**Comment by Megabyte918** [comment]
# #638
