### ISSUE TITLE
TypeError: Argument cb must be a function

### ISSUE THREAD

**Issue by MrSonicMaster** [AJS-development/Ogar-unlimited#997]
When it starts up, i end up getting this error:
TypeError: Argument cb must be a function

This is the full log:
     [INFO] Loading Config Files...
[INFO] Loading C:/Users/clock/Desktop/OgarNew/core/../settings/advConfig.ini
[INFO] Loading C:/Users/clock/Desktop/OgarNew/core/../settings/clientConfig.ini
[INFO] Loading C:/Users/clock/Desktop/OgarNew/core/../settings/config.ini
[INFO] Loading C:/Users/clock/Desktop/OgarNew/core/../settings/override.ini
[INFO] Your unique id is: eZ9bBCrxmG
[INFO] Loading plugins
[TypeError: Argument cb must be a function]
[INFO] Starting ConsoleService

Also, when i try to join the game i end up crashing Agar.io with this error:

agario.core.js:7 exception thrown: IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-28923) is negative.,Error: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-28923) is negative.
    at Error (native)
    at Array.<anonymous> (http://agar.io/agario.core.js:9:7328)
    at _594210e9 (http://agar.io/agario.core.js:10:14701)
    at Mc (http://agar.io/agario.core.js:11:47357)
    at rc (http://agar.io/agario.core.js:11:19456)
    at Rb (http://agar.io/agario.core.js:11:6457)
    at Array.Qb (http://agar.io/agario.core.js:11:6193)
    at Lr (http://agar.io/agario.core.js:14:91152)
    at Object.C (http://agar.io/agario.core.js:7:5792)
    at http://agar.io/agario.core.js:6:495c.printErr @ agario.core.js:7$a @ agario.core.js:9Ra.e.e.aa @ agario.core.js:6nrWrapper @ (index):25
(index):25 Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-28923) is negative.

(https://gyazo.com/d2dc6bc89523d629385a5c42421533cc)

**Comment by Agarian** [comment]
First off, use node v5.9.0
Second off, use http://play.ogarul.tk
